#!/bin/bash
# SessionStart hook for Claude Code sessions.
#
# Jobs 1 and 2 are remote-only (they no-op when $CLAUDE_CODE_REMOTE is unset, so
# local dev sessions are unaffected and running `claude` against your working
# tree won't reinstall on every launch). Job 3 runs everywhere.
#
# 1. Install a `gh` shim that routes the GitHub CLI around the outbound HTTPS
#    proxy. The agent egress proxy (HTTPS_PROXY) enforces a policy that blocks
#    some api.github.com operations — notably `gh run watch`, which long-polls —
#    so the gh-based skills (/watch-ci, /check-merge, /finalize, …) stall. gh
#    talks only to GitHub hosts and works fine connecting directly, so we strip
#    the proxy for gh alone. Everything else that legitimately needs the proxy
#    is untouched.
#
# 2. Re-sync dependencies. Remote/web sessions can resume with a stale
#    dependency tree if the lockfile advanced since the environment snapshot was
#    built (the setup script runs once at snapshot build time, then is cached —
#    see https://code.claude.com/docs/en/claude-code-on-the-web#setup-scripts).
#    Re-running on every session start keeps the install tree tracking the
#    current lockfile.
#
# TODO (new project): implement dependency install for your stack, e.g.
#   pnpm install --frozen-lockfile     # Node / pnpm
#   poetry install --sync              # Python / poetry
#   cargo fetch                        # Rust
#   go mod download                    # Go
#
# Until the install line is implemented, job 2 no-ops cleanly; job 1 works as-is.
#
# 3. Print the operator's GitHub handle into the session context, so the agent
#    starts the session already knowing who it is talking to instead of spending
#    a turn resolving it. See `.claude/skills/plainly/voice.md`, which keys its
#    operator entries on that handle.

set -euo pipefail

# --- 1. Install the proxy-stripping gh shim -------------------------------
# $HOME/.local/bin is first on PATH, so a `gh` here shadows the real binary for
# every Bash tool shell this session spawns. The VM is ephemeral and the hook
# runs on every startup|resume, so recreating the shim each session is correct.
install_gh_shim() {
  local shim_dir="${HOME}/.local/bin"
  # Resolve the real gh, ignoring any shim a previous run left in shim_dir, so
  # the shim never ends up exec'ing itself.
  local real_gh
  real_gh="$(PATH="$(printf '%s' "$PATH" | tr ':' '\n' | grep -vFx "$shim_dir" | paste -sd: -)" command -v gh || true)"
  if [ -z "$real_gh" ]; then
    # stdout, not stderr: Claude Code folds a SessionStart hook's stdout into
    # the session context, and this notice is the only signal that the
    # environment setup script is unset or missing the gh install.
    cat <<'MSG'
session-start: `gh` is not on PATH, so the proxy shim was not installed.

Agent: relay this to the operator before running anything that needs `gh`
(most of the PR loop does). The environment setup script for this Claude Code
environment is either unset or does not install the GitHub CLI. They set it in
the session composer: the environment picker -> Cloud -> the environment's gear
icon. It needs at least:

    apt-get install -y gh

The script runs once when the environment snapshot is built, so the session has
to be restarted for it to take effect.
MSG
    return 0
  fi

  mkdir -p "$shim_dir"
  cat > "${shim_dir}/gh" <<EOF
#!/bin/bash
# Auto-generated by .claude/hooks/session-start.sh — do not edit by hand.
# Routes gh around the outbound HTTPS proxy (which blocks some api.github.com
# operations, e.g. long-polling \`gh run watch\`). See the hook for rationale.
exec env -u HTTPS_PROXY -u https_proxy ${real_gh} "\$@"
EOF
  chmod +x "${shim_dir}/gh"
}

if [ "${CLAUDE_CODE_REMOTE:-}" = "true" ]; then
  install_gh_shim

  # --- 2. Keep dependencies in sync with the lockfile ---------------------
  cd "${CLAUDE_PROJECT_DIR:-$(pwd)}"

  # TODO: install dependencies for your stack
fi

# --- 3. Name the operator ------------------------------------------------
# Outside the remote gate: the agent needs the handle wherever it runs, and `gh`
# reaches the API through the proxy as well as around it, so this works whether
# or not job 1 installed the shim.
#
# `.type` is the load-bearing field: a token minted for a human names that human
# (`User`), one of the agent's own names the agent (`Bot`), and only the first
# answers "who am I talking to". Hence two messages rather than a bare login,
# which would be trusted in exactly the case where it is wrong.
name_the_operator() {
  local identity
  identity="$(gh api user --jq '[.login, .type] | @tsv' 2>/dev/null || true)"

  if [ -z "$identity" ]; then
    echo "session-start: the operator's GitHub handle is unresolved (\`gh\` is unavailable or could not reach the API). Ask them for it if you need their operators.md entry."
    return 0
  fi

  local login="${identity%%	*}" type="${identity##*	}"

  if [ "$type" = "User" ]; then
    echo "session-start: the operator is @${login} — the GitHub token in this session is that user's own. Apply their entry in .claude/skills/plainly/operators.md, if they have one."
  else
    echo "session-start: the GitHub token in this session belongs to ${login}, a ${type} account — that is the agent's own identity, not the operator's. Ask the operator for their handle before applying any operators.md entry."
  fi
}

name_the_operator
